package org.dyndns.doujindb.db.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.dyndns.doujindb.db.cayenne.Content;
import org.dyndns.doujindb.db.cayenne.Book;

/**
 * Class _Contains was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _Contains extends CayenneDataObject {

    public static final String BOOK_CONTAINS_PROPERTY = "bookContains";
    public static final String CONTENT_CONTAINS_PROPERTY = "contentContains";

    public static final String BOOK_ID_PK_COLUMN = "BOOK_ID";
    public static final String CONTENT_ID_PK_COLUMN = "CONTENT_ID";

    public void setBookContains(Book bookContains) {
        setToOneTarget("bookContains", bookContains, true);
    }

    public Book getBookContains() {
        return (Book)readProperty("bookContains");
    }


    public void setContentContains(Content contentContains) {
        setToOneTarget("contentContains", contentContains, true);
    }

    public Content getContentContains() {
        return (Content)readProperty("contentContains");
    }

}
