package org.dyndns.doujindb.db.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ConventionAlias was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ConventionAlias extends CayenneDataObject {

    public static final String TAG_NAME_PROPERTY = "tagName";

    public static final String ID_PK_COLUMN = "ID";

    public void setTagName(String tagName) {
        writeProperty("tagName", tagName);
    }
    public String getTagName() {
        return (String)readProperty("tagName");
    }

    protected abstract void postAdd();

}
