package org.dyndns.doujindb.db.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.dyndns.doujindb.db.cayenne.Convention;

/**
 * Class _ConventionAlias was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _ConventionAlias extends CayenneDataObject {

    public static final String TAG_NAME_PROPERTY = "tagName";
    public static final String CONVENTIONALIAS_PROPERTY = "conventionalias";

    public static final String CONVENTION_ID_PK_COLUMN = "CONVENTION_ID";
    public static final String ID_PK_COLUMN = "ID";

    public void setTagName(String tagName) {
        writeProperty("tagName", tagName);
    }
    public String getTagName() {
        return (String)readProperty("tagName");
    }

    public void setConventionalias(Convention conventionalias) {
        setToOneTarget("conventionalias", conventionalias, true);
    }

    public Convention getConventionalias() {
        return (Convention)readProperty("conventionalias");
    }


    protected abstract void postAdd();

}
