package org.dyndns.doujindb.db.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.dyndns.doujindb.db.cayenne.Content;

/**
 * Class _ContentAlias was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _ContentAlias extends CayenneDataObject {

    public static final String TAG_NAME_PROPERTY = "tagName";
    public static final String CONTENTALIAS_PROPERTY = "contentalias";

    public static final String CONTENT_ID_PK_COLUMN = "CONTENT_ID";
    public static final String ID_PK_COLUMN = "ID";

    public void setTagName(String tagName) {
        writeProperty("tagName", tagName);
    }
    public String getTagName() {
        return (String)readProperty("tagName");
    }

    public void setContentalias(Content contentalias) {
        setToOneTarget("contentalias", contentalias, true);
    }

    public Content getContentalias() {
        return (Content)readProperty("contentalias");
    }


    protected abstract void postAdd();

}
