package org.dyndns.doujindb.db.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.dyndns.doujindb.db.cayenne.Artist;
import org.dyndns.doujindb.db.cayenne.Book;

/**
 * Class _DrawnBy was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _DrawnBy extends CayenneDataObject {

    public static final String ARTIST_DRAWNBY_PROPERTY = "artistDrawnby";
    public static final String BOOK_DRAWNBY_PROPERTY = "bookDrawnby";

    public static final String ARTIST_ID_PK_COLUMN = "ARTIST_ID";
    public static final String BOOK_ID_PK_COLUMN = "BOOK_ID";

    public void setArtistDrawnby(Artist artistDrawnby) {
        setToOneTarget("artistDrawnby", artistDrawnby, true);
    }

    public Artist getArtistDrawnby() {
        return (Artist)readProperty("artistDrawnby");
    }


    public void setBookDrawnby(Book bookDrawnby) {
        setToOneTarget("bookDrawnby", bookDrawnby, true);
    }

    public Book getBookDrawnby() {
        return (Book)readProperty("bookDrawnby");
    }
}
