package org.dyndns.doujindb.db.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.dyndns.doujindb.db.cayenne.Artist;
import org.dyndns.doujindb.db.cayenne.Circle;

/**
 * Class _MemberOf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _MemberOf extends CayenneDataObject {

    public static final String ARTIST_MEMBEROF_PROPERTY = "artistMemberof";
    public static final String CIRCLE_MEMBEROF_PROPERTY = "circleMemberof";

    public static final String ARTIST_ID_PK_COLUMN = "ARTIST_ID";
    public static final String CIRCLE_ID_PK_COLUMN = "CIRCLE_ID";

    public void setArtistMemberof(Artist artistMemberof) {
        setToOneTarget("artistMemberof", artistMemberof, true);
    }

    public Artist getArtistMemberof() {
        return (Artist)readProperty("artistMemberof");
    }


    public void setCircleMemberof(Circle circleMemberof) {
        setToOneTarget("circleMemberof", circleMemberof, true);
    }

    public Circle getCircleMemberof() {
        return (Circle)readProperty("circleMemberof");
    }
}
