package org.dyndns.doujindb.db.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.dyndns.doujindb.db.cayenne.Book;
import org.dyndns.doujindb.db.cayenne.Parody;

/**
 * Class _ParodyOf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _ParodyOf extends CayenneDataObject {

    public static final String BOOK_PARODYOF_PROPERTY = "bookParodyof";
    public static final String PARODY_PARODYOF_PROPERTY = "parodyParodyof";

    public static final String BOOK_ID_PK_COLUMN = "BOOK_ID";
    public static final String PARODY_ID_PK_COLUMN = "PARODY_ID";

    public void setBookParodyof(Book bookParodyof) {
        setToOneTarget("bookParodyof", bookParodyof, true);
    }

    public Book getBookParodyof() {
        return (Book)readProperty("bookParodyof");
    }


    public void setParodyParodyof(Parody parodyParodyof) {
        setToOneTarget("parodyParodyof", parodyParodyof, true);
    }

    public Parody getParodyParodyof() {
        return (Parody)readProperty("parodyParodyof");
    }

}
