package org.dyndns.doujindb.db.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.dyndns.doujindb.db.cayenne.Book;

/**
 * Class _Rating was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _Rating extends CayenneDataObject {

    public static final String VALUE_PROPERTY = "value";
    public static final String RATINGOF_PROPERTY = "ratingof";

    public static final String ID_PK_COLUMN = "ID";

    public void setValue(Integer value) {
        writeProperty("value", value);
    }
    public Integer getValue() {
        return (Integer)readProperty("value");
    }

    public void addToRatingof(Book obj) {
        addToManyTarget("ratingof", obj, true);
    }
    public void removeFromRatingof(Book obj) {
        removeToManyTarget("ratingof", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Book> getRatingof() {
        return (List<Book>)readProperty("ratingof");
    }


}
