package org.dyndns.doujindb.db.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.dyndns.doujindb.db.cayenne.Book;

/**
 * Class _Type was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("serial")
public abstract class _Type extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String TYPEOF_PROPERTY = "typeof";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToTypeof(Book obj) {
        addToManyTarget("typeof", obj, true);
    }
    public void removeFromTypeof(Book obj) {
        removeToManyTarget("typeof", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Book> getTypeof() {
        return (List<Book>)readProperty("typeof");
    }


}
